# Generated by Django 6.0.6 on 2026-06-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='000000', max_length=6),
            preserve_default=False,
        ),
    ]
