# Generated by Django 6.0.6 on 2026-06-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zipcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
    ]
