# Generated by Django 6.0.6 on 2026-06-18 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zipcode'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (collection_name)
                          VALUES ('collection1')
        """, """
            DELETE FROM store_collection
            WHERE collection_name='collection1'
        """)
    ]
