# Generated by Django 6.0.6 on 2026-06-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20260618_0136'),
        ('store', '0005_rename_first_name_customer_given_name'),
    ]

    operations = [
    ]
